### ISSUE TITLE
用 CMake 为 ijkplayer 增加 android native debug 支持

### ISSUE THREAD

**Issue by befovy** [befovy/blogback#5]
给 ijkplayer 增加了 cmake 构建方式，支持在 android studio 中进行 c 代码断点调试。  
直接上手请前往 https://github.com/befovy/ijkplayer#build-android-via-cmake

如果想了解一下整个过程请继续阅读本文。

**Comment by xuantiandou** [comment]
我下载了你的源码 重新编译后，能跑起来但是还是不能debug，请问是什么情况？
